name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu al
      uses: actions/checkout@v3

    - name: Docker Hub'a giris yap
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker image build et ve push et
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          myprecious1987/devops-demo:latest
          myprecious1987/devops-demo:${{ github.sha }}

    - name: SSH key hazirla
      run: |
        mkdir -p ~/.ssh
        printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
        chmod 600 ~/.ssh/github-actions
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: SSH ile Kubernetes'e deploy et
      run: |
        ssh -i ~/.ssh/github-actions -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "kubectl apply -f ~/devops-demo/k8s/namespace.yaml && \
           kubectl apply -f ~/devops-demo/k8s/deployment.yaml && \
           kubectl apply -f ~/devops-demo/k8s/service.yaml && \
           kubectl set image deployment/devops-demo devops-demo=myprecious1987/devops-demo:${{ github.sha }} -n devops-demo && \
           kubectl rollout status deployment/devops-demo -n devops-demo"
